package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/fiftyk/claude-switcher/internal/profile"
)

// ExportFormat 导出格式
type ExportFormat string

const (
	FormatJSON  ExportFormat = "json"
	FormatYAML  ExportFormat = "yaml"
	FormatShell ExportFormat = "shell"
)

// ExportProfileToJSON 将配置导出为 JSON 格式
func ExportProfileToJSON(p *profile.Profile) ([]byte, error) {
	exportData := map[string]interface{}{
		"name":         p.Name,
		"auth_token":   p.AuthToken,
		"base_url":     p.BaseURL,
		"http_proxy":   p.HTTPProxy,
		"https_proxy":  p.HTTPSProxy,
		"model":        p.Model,
		"custom_vars":  p.EnvVars,
	}

	return json.MarshalIndent(exportData, "", "  ")
}

// ExportProfileToYAML 将配置导出为 YAML 格式
func ExportProfileToYAML(p *profile.Profile) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("name: " + p.Name + "\n")
	if p.AuthToken != "" {
		sb.WriteString("auth_token: " + p.AuthToken + "\n")
	}
	if p.BaseURL != "" {
		sb.WriteString("base_url: " + p.BaseURL + "\n")
	}
	if p.HTTPProxy != "" {
		sb.WriteString("http_proxy: " + p.HTTPProxy + "\n")
	}
	if p.HTTPSProxy != "" {
		sb.WriteString("https_proxy: " + p.HTTPSProxy + "\n")
	}
	if p.Model != "" {
		sb.WriteString("model: " + p.Model + "\n")
	}
	if len(p.EnvVars) > 0 {
		sb.WriteString("custom_vars:\n")
		for k, v := range p.EnvVars {
			sb.WriteString("  " + k + ": " + v + "\n")
		}
	}

	return []byte(sb.String()), nil
}

// ExportProfileToShell 将配置导出为 Shell 变量格式
func ExportProfileToShell(p *profile.Profile) ([]byte, error) {
	var sb strings.Builder

	sb.WriteString("# Claude Switcher Profile Export\n")
	sb.WriteString("# Generated by claude-switcher\n\n")

	sb.WriteString("export CLAUDE_SWITCHER_PROFILE=\"" + p.Name + "\"\n")
	if p.AuthToken != "" {
		sb.WriteString("export ANTHROPIC_AUTH_TOKEN=\"" + p.AuthToken + "\"\n")
	}
	if p.BaseURL != "" {
		sb.WriteString("export ANTHROPIC_BASE_URL=\"" + p.BaseURL + "\"\n")
	}
	if p.HTTPProxy != "" {
		sb.WriteString("export http_proxy=\"" + p.HTTPProxy + "\"\n")
		sb.WriteString("export https_proxy=\"" + p.HTTPProxy + "\"\n")
	}
	if p.Model != "" {
		sb.WriteString("export ANTHROPIC_MODEL=\"" + p.Model + "\"\n")
	}
	for k, v := range p.EnvVars {
		sb.WriteString("export " + k + "=\"" + v + "\"\n")
	}

	return []byte(sb.String()), nil
}

// ExportProfile 将配置导出为指定格式
func ExportProfile(p *profile.Profile, format ExportFormat) ([]byte, error) {
	switch format {
	case FormatJSON:
		return ExportProfileToJSON(p)
	case FormatYAML:
		return ExportProfileToYAML(p)
	case FormatShell:
		return ExportProfileToShell(p)
	default:
		return nil, fmt.Errorf("unsupported export format: %s", format)
	}
}

// ExportAllProfiles 导出所有配置为 JSON
func ExportAllProfiles(profilesDir string) ([]byte, error) {
	names, err := profile.ListProfiles(profilesDir)
	if err != nil {
		return nil, err
	}

	var profiles []map[string]interface{}
	for _, name := range names {
		p, err := profile.LoadProfile(profilesDir, name)
		if err != nil {
			continue
		}

		profileData := map[string]interface{}{
			"name":        p.Name,
			"auth_token":  p.AuthToken,
			"base_url":    p.BaseURL,
			"http_proxy":  p.HTTPProxy,
			"https_proxy": p.HTTPSProxy,
			"model":       p.Model,
			"custom_vars": p.EnvVars,
		}
		profiles = append(profiles, profileData)
	}

	exportData := map[string]interface{}{
		"version":   "1.0",
		"generated": "claude-switcher",
		"profiles":  profiles,
	}

	return json.MarshalIndent(exportData, "", "  ")
}

// SaveExportToFile 保存导出内容到文件
func SaveExportToFile(data []byte, profileName string, format ExportFormat) (string, error) {
	homeDir, err := os.UserHomeDir()
	if err != nil {
		return "", fmt.Errorf("cannot get home directory: %w", err)
	}

	exportDir := filepath.Join(homeDir, ".claude-switcher", "exports")
	if err := os.MkdirAll(exportDir, 0755); err != nil {
		return "", fmt.Errorf("cannot create export directory: %w", err)
	}

	filename := filepath.Join(exportDir, profileName+"."+string(format))
	if err := os.WriteFile(filename, data, 0644); err != nil {
		return "", fmt.Errorf("cannot write file: %w", err)
	}

	return filename, nil
}

// PrintExportHelp 打印导出帮助信息
func PrintExportHelp() {
	fmt.Println("\n导出格式:")
	fmt.Println("  json   - JSON 格式，适合程序处理")
	fmt.Println("  yaml   - YAML 格式，易读")
	fmt.Println("  shell  - Shell 变量格式，可直接 source")
	fmt.Println()
	fmt.Println("用法:")
	fmt.Println("  claude-switcher --export <配置名> [格式]")
	fmt.Println("  claude-switcher --export-all          导出所有配置")
	fmt.Println()
}
